# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bcad5ce5be46fd24c3d0fec1b9820be0c98e78dfdcebb59c774869d5ba5192f8549ad78dfffbbb188c361fd22517cad58d6b36987e2cfb4bf878894f6036f8

test:
  secret_key_base: d6a53ed1e7c758e81c8b1fd840e26fdd0568a3f092d789cbe455dbae0ac6485d788dc59eb077c500f96b111b77c5b893204a73cd63ef76adef6b0dd633e36e74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
